-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: cf550fcab3f12015f8676b8278b30e1a5bc10e70
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
